server {
    listen 80;
    server_name 57.131.16.162 80.225.90.151;
    root /var/www/veterinari/frontend/dist;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
